// 30 產業
const INDUSTRIES = [
  { id: 'tech-semi', zh: '科技／半導體／電子', en: 'Tech & Semiconductor', pain: '高科技高壓力，老闆秒回信、會議塞滿一日，秘書連喝水時間都沒有。' },
  { id: 'software', zh: '軟體／網路／資訊服務', en: 'Software & Internet', pain: '工程師講術語、PM 改規格、老闆要 KPI ，三邊翻譯全靠你。' },
  { id: 'telecom', zh: '電信／通訊', en: 'Telecom', pain: '24 小時不能斷線，跨部門報表 24 小時內就要交。' },
  { id: 'media', zh: '傳播／媒體／出版', en: 'Media & Publishing', pain: '截稿日永遠是昨天，老闆的點子比稿子多。' },
  { id: 'marketing', zh: '廣告／行銷／公關', en: 'Advertising & PR', pain: '提案前一晚改八版，會議紀錄要美又要快。' },
  { id: 'finance', zh: '金融／保險／投資', en: 'Finance & Insurance', pain: '法遵、合規、報告，每一份文件都不能有錯。' },
  { id: 'realestate', zh: '不動產／建築／營造', en: 'Real Estate & Construction', pain: '工地、會議、客戶、老闆四線奔波，紙本合約堆成山。' },
  { id: 'mfg-machine', zh: '製造－機械／金屬', en: 'Manufacturing — Machinery', pain: '老闆在工廠、客戶在海外、文件全是工程術語。' },
  { id: 'mfg-electric', zh: '製造－電力／電機', en: 'Manufacturing — Electric', pain: '報價單、規格書每天上百份，格式還都不一樣。' },
  { id: 'mfg-auto', zh: '製造－汽機車／交通工具', en: 'Manufacturing — Automotive', pain: '供應鏈四個時區開會，會議紀錄三語齊發。' },
  { id: 'mfg-chem', zh: '製造－化工／材料', en: 'Manufacturing — Chemical', pain: 'MSDS、規格、合約厚到看不完，老闆 10 分鐘後要結論。' },
  { id: 'mfg-paper', zh: '製造－紙／木／纖維', en: 'Manufacturing — Paper & Textile', pain: '老闆是工匠出身，交辦永遠用語音、永遠講重點不講細節。' },
  { id: 'mfg-food', zh: '製造－食品／飲料', en: 'Manufacturing — Food & Beverage', pain: '客戶名單、訂單、宅配、節慶送禮，全年無休。' },
  { id: 'mfg-other', zh: '製造－其他消費品', en: 'Manufacturing — Consumer Goods', pain: '展會、訂單、樣品、客訴，秘書一個人當三個人用。' },
  { id: 'retail', zh: '零售／批發／貿易', en: 'Retail & Trade', pain: '海外客戶、雙語信件、報價單、樣品寄送，每天像戰場。' },
  { id: 'logistics', zh: '物流／運輸／倉儲', en: 'Logistics & Warehousing', pain: '時效就是金錢，差勤、排班、客訴回應一秒都不能慢。' },
  { id: 'hospitality', zh: '餐飲／住宿／休閒', en: 'Hospitality & F&B', pain: '老闆現場巡店、訂位、訂房、客訴，全靠秘書遠端搞定。' },
  { id: 'medical', zh: '醫療／健康／美容', en: 'Healthcare & Beauty', pain: '病歷、預約、保險、行政表單，一個錯字都會出大事。' },
  { id: 'education', zh: '教育／補習', en: 'Education', pain: '家長、學生、老師、董事會，四方訊息都從你手上過。' },
  { id: 'hr-consult', zh: '人力資源／顧問', en: 'HR & Consulting', pain: '客戶提案、面試安排、報表、合約，做的事情比顧問還多。' },
  { id: 'design', zh: '設計／專業服務', en: 'Design & Professional Services', pain: '老闆是創意人，今天的決策明天會變，你要追著改。' },
  { id: 'energy', zh: '能源／環境／公用事業', en: 'Energy & Utilities', pain: '法規、ESG 報告、政府公文，每份都要你校對三次。' },
  { id: 'agri', zh: '農業／畜牧／水產', en: 'Agriculture & Fishery', pain: '老闆在田裡、客戶在城裡、補助申請永遠在最後一天。' },
  { id: 'auto-svc', zh: '汽機車服務', en: 'Auto Services', pain: '客戶來電、維修進度、零件訂購，老闆要你五分鐘內回。' },
  { id: 'security', zh: '保全／物業', en: 'Security & Property', pain: '住戶投訴、巡邏紀錄、月報，紙本作業多到崩潰。' },
  { id: 'biotech', zh: '生技／研發', en: 'Biotech & R&D', pain: '專利、論文、實驗紀錄，老闆要你看懂並濃縮成 1 頁。' },
  { id: 'gov-npo', zh: '政府／非營利', en: 'Government & NPO', pain: '公文、結案報告、計畫書，格式比內容更重要。' },
  { id: 'funeral', zh: '殯葬／其他生活服務', en: 'Funeral & Lifestyle', pain: '家屬情緒、流程細節、合約，每件事都不能出錯。' },
  { id: 'museum', zh: '圖書館／博物館', en: 'Library & Museum', pain: '展覽、典藏、申請補助、新聞稿，一個人當八個人用。' },
  { id: 'defense', zh: '國防', en: 'Defense', pain: '機密、流程、會議紀錄，每份文件都要過三層審查。' },
];

// 20 課程
const COURSES = [
  { n: '01', title: '老闆錄音祕笈', subtitle: '會議 10 分鐘交件術', timer: '10 分鐘',
    pain: '開會邊打字邊記重點，打到第二點老闆已經講到第五點。',
    solve: '手機錄音 → AI 轉逐字稿 → AI 產出三版（重點版／完整版／待辦清單）。',
    take: '個人化「會議錄音 → 三版交件」工作流 + 3 套提示詞模板。' },
  { n: '02', title: '名片秒掃歸檔術', subtitle: '100 張 15 分鐘結案', timer: '15 分鐘',
    pain: '抽屜、外套、桌角一堆名片，老闆要找客戶電話翻半天。',
    solve: '名片堆連續拍 → AI 批次辨識 → 一鍵輸出 Excel 與通訊錄格式。',
    take: '自家公司版的名片資料庫雛形（當場匯入）。' },
  { n: '03', title: '老闆 LINE 翻譯機', subtitle: '30 秒看懂語音轉文字', timer: '30 秒',
    pain: '老闆 500 字 LINE 沒標點沒重點，看半天不知道要做什麼。',
    solve: '貼給 AI → 30 秒翻譯成「3 件要做的事 + 2 個要回的問題 + 1 個期限」。',
    take: '3 種老闆語氣的翻譯模板（溫和／急躁／抽象）。' },
  { n: '04', title: '雙語接待一小時套裝', subtitle: '日商美商臨時來訪不慌', timer: '1 小時',
    pain: '日商美商臨時來訪，歡迎稿、接待詞、簡報翻譯、議程全要雙語。',
    solve: '中文底稿丟 AI → 英／日雙版齊出，1 小時全包。',
    take: '雙語接待包模板（歡迎詞／議程／餐敘開場）。' },
  { n: '05', title: '合約地雷掃描術', subtitle: '100 頁合約 5 分鐘交報告', timer: '5 分鐘',
    pain: '老闆 10 分鐘後開會，丟來 100 頁合約叫你告訴他「有沒有雷」。',
    solve: 'PDF 丟 AI，問六大關鍵條款，5 分鐘條列交件。',
    take: '合約審閱六問提示詞 + 紅綠燈摘要模板。' },
  { n: '06', title: '月底對帳信量產術', subtitle: '80 封 10 分鐘生好', timer: '10 分鐘',
    pain: '每月 80 個客戶的客製化通知信，一個個改稱謂改金額。',
    solve: 'AI + Excel 名單批次套用個人化 email，手動複審即可發。',
    take: '可反覆使用的「名單 → 個人化信」批次工作流。' },
  { n: '07', title: '老闆記憶還原術', subtitle: '3 分鐘定位陳年案件', timer: '3 分鐘',
    pain: '老闆只記片段：「去年那個科技業女客戶的那個案子」，你翻 Gmail 翻一下午。',
    solve: '資料彙整給 AI，自然語言精準定位。',
    take: '個人化資料檢索工作流。' },
  { n: '08', title: '三天出差準備包', subtitle: '2 小時齊活', timer: '2 小時',
    pain: '老闆 3 天後出差東京，機票、飯店、會面、資料邊做邊漏。',
    solve: 'AI 生「出差清單 + 行程表 + 資料包目錄 + 通知信」。',
    take: '出差準備 SOP 模板（國內／東亞／歐美）。' },
  { n: '09', title: '照片訂位術', subtitle: '一張照片 30 秒搞定', timer: '30 秒',
    pain: '老闆只傳一張餐廳照片說「幫我訂」。',
    solve: '圖片丟 AI 辨識 → 店名、電話、菜單、訂位連結一次給。',
    take: '圖片資訊反查的通用工作流。' },
  { n: '10', title: '差勤對帳魔法', subtitle: '系統 vs LINE 10 分鐘對完', timer: '10 分鐘',
    pain: '差勤系統 vs LINE 請假紀錄一個個手動比對到崩潰。',
    solve: '雙邊資料丟 AI 交叉比對，輸出差異清單。',
    take: '差勤交叉比對提示詞 + 差異報表模板。' },
  { n: '11', title: '致辭稿三版生成器', subtitle: '20 分鐘交三種調性', timer: '20 分鐘',
    pain: '節慶老闆要 3 分鐘致辭稿，寫來寫去都那幾句。',
    solve: 'AI 產三種調性（溫暖／幽默／激勵），選一個微調。',
    take: '致辭稿三調性提示詞 + 公司慣用語錄。' },
  { n: '12', title: '送禮名單炸不開', subtitle: '50 份卡片 30 分鐘完稿', timer: '30 分鐘',
    pain: '中秋 50 個客戶禮盒名單、地址、卡片文字都不同。',
    solve: 'AI 依分層自動生成個人化卡片 + 宅配單。',
    take: '節慶送禮全流程模板。' },
  { n: '13', title: '老闆碎念解讀術', subtitle: '即時錄音 → 待辦', timer: '即時',
    pain: '老闆語音一口氣 3 分鐘「這個還有那個還有另外那個」。',
    solve: '錄音 → AI 拆成「待辦清單 + 期限 + 負責人」。',
    take: '即時錄音 → 待辦拆解工作流（iOS／Android）。' },
  { n: '14', title: 'Excel 美顏術', subtitle: '10 分鐘交一份漂亮報表', timer: '10 分鐘',
    pain: '老闆要報表「弄漂亮、上色、加統計」，你 Excel 不熟。',
    solve: 'AI 直接寫公式／VBA／格式指令，一鍵美化。',
    take: '最常被要求的 10 種 Excel 美化提示詞。' },
  { n: '15', title: '報價單百變工廠', subtitle: '3 分鐘一份', timer: '3 分鐘',
    pain: '每個客戶要的報價單格式都不同（含稅／分期／附照／組合）。',
    solve: 'AI 依需求 + 產品資料自動生成 Word／PDF。',
    take: '可組合式報價單模板 + 客製化生成提示詞。' },
  { n: '16', title: '300 人請柬不出錯', subtitle: '20 分鐘排好列印隊', timer: '20 分鐘',
    pain: '300 份請柬要套印姓名、職稱、桌號，還不能出錯丟臉。',
    solve: 'AI 協助郵件合併 + 校對清單 + 錯誤檢查。',
    take: '大量名單製作物的校對 SOP。' },
  { n: '17', title: '老闆社群代筆術', subtitle: '一週 po 文 10 分鐘搞定', timer: '10 分鐘',
    pain: '老闆推 IG／LinkedIn 給你做，你也沒靈感又要配圖。',
    solve: 'AI 依老闆風格生 3 種文案 + 自動配圖 + 排程。',
    take: '老闆專屬語氣提示詞 + 配圖生成流程。' },
  { n: '18', title: '總週報自動整併', subtitle: '5 份合 1 份只要 15 分鐘', timer: '15 分鐘',
    pain: '5 個部門 5 種格式週報，要合成老闆版總週報。',
    solve: '5 份一次丟 AI → 整合 + 標重點 + 比對上週。',
    take: '週報合併通用模板 + 重點凸顯格式。' },
  { n: '19', title: '訪客數據洞察', subtitle: '20 分鐘出 insight', timer: '20 分鐘',
    pain: '老闆突然問「這半年誰來最多次、平均停留多久、目的是什麼」。',
    solve: '訪客登記本拍照／匯出 → AI 產月份分析 + 排行 + 圖表。',
    take: '訪客資料洞察模板。' },
  { n: '20', title: '跨時區會議終結 10 輪信', subtitle: '5 分鐘定案三方時段', timer: '5 分鐘',
    pain: '台日美三方來回信件 10 輪才能敲定時間。',
    solve: 'AI 分析各方 calendar 找交集 + 三時區通知一次寫好。',
    take: '跨時區協調提示詞 + 三語時差通知信模板。' },
];

window.INDUSTRIES = INDUSTRIES;
window.COURSES = COURSES;
